name: Update JSON Files

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create temp directory and download files
        run: |
          mkdir -p /tmp/ha-files
          cd /tmp/ha-files
          curl -o stable.json https://version.home-assistant.io/stable.json
          curl -o beta.json https://version.home-assistant.io/beta.json
          curl -o dev.json https://version.home-assistant.io/dev.json
          sed -i \
            -e 's|https://os-artifacts.home-assistant.io/|https://github.com/ameriDroid/HA-operating-system/releases/download/|g' \
            -e 's|"supervisor": "homeassistant/|"supervisor": "ameridroid/|g' \
            -e 's|"supervisor": "ghcr.io/home-assistant|"supervisor": "ghcr.io/ameridroid|g' \
            stable.json beta.json dev.json

      - name: Setup git config
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"

      - name: Switch to gh-pages and update
        run: |
          git fetch origin gh-pages
          git checkout gh-pages || git checkout -b gh-pages
          git rm -rf stable.json beta.json dev.json || true
          cp /tmp/ha-files/* .
          git add .
          git commit -m "Update JSON files" || true
          git push origin gh-pages --force || true